.TH "adj" 3 "Fase2 - EDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adj
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdest\fP"
.br
.ti -1c
.RI "struct \fBadj\fP * \fBprox\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Fase2 - EDA from the source code\&.
