.TH "utils.c" 3 "Fase2 - EDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utils.c
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br
\fR#include 'utils\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcarregarMatrizParaGrafo\fP (const char *filename, \fBGrafo\fP *g)"
.br
.RI "Lê uma matriz de antenas a partir do ficheiro de texto e constrói o grafo\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Daniel Vilaça (a16939@alunos.ipca.pt) 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2025-05-18
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2025 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int carregarMatrizParaGrafo (const char * filename, \fBGrafo\fP * g)"

.PP
Lê uma matriz de antenas a partir do ficheiro de texto e constrói o grafo\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP Nome do ficheiro da matriz de antenas 
.br
\fIg\fP Apontador para o grafo a ser preenchido 
.RE
.PP
\fBReturns\fP
.RS 4
Return 1 se o carregamento for bem-sucedido ou 0 em caso de erro 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Fase2 - EDA from the source code\&.
