.TH "vertice" 3 "Fase2 - EDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vertice
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "char \fBfreq\fP"
.br
.ti -1c
.RI "\fBAdj\fP * \fBlista\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Fase2 - EDA from the source code\&.
