.TH "Antena" 3 "EDA_16939_Fase1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Antena \- Estrutura que representa uma antena\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <antena\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBfreq\fP"
.br
.ti -1c
.RI "int \fBlinha\fP"
.br
.ti -1c
.RI "int \fBcoluna\fP"
.br
.ti -1c
.RI "struct \fBAntena\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Estrutura que representa uma antena\&. 
.PP
Definition at line \fB20\fP of file \fBantena\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Antena::coluna"

.PP
Definition at line \fB22\fP of file \fBantena\&.h\fP\&.
.SS "char Antena::freq"

.PP
Definition at line \fB21\fP of file \fBantena\&.h\fP\&.
.SS "int Antena::linha"

.PP
Definition at line \fB22\fP of file \fBantena\&.h\fP\&.
.SS "struct \fBAntena\fP* Antena::next"

.PP
Definition at line \fB23\fP of file \fBantena\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EDA_16939_Fase1 from the source code\&.
