.TH "main.c" 3 "EDA_16939_Fase1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include 'antena\&.h'\fP
.br
\fR#include 'matriz\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "Função principal do programa\&. Exibe menu para o utilizador interagir com a matriz e antenas\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Daniel Vilaça (a16939@alunos.ipca.pt) 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2025-03-30
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2025 
.RE
.PP

.PP
Definition in file \fBmain\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Função principal do programa\&. Exibe menu para o utilizador interagir com a matriz e antenas\&. Permite carregar matriz de ficheiro, inserir/remover antenas, visualizar matriz e os efeitos nefastos

.PP
\fBReturns\fP
.RS 4
int Código de retorno do programa 
.RE
.PP

.PP
Definition at line \fB25\fP of file \fBmain\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for EDA_16939_Fase1 from the source code\&.
