.TH "Node" 3 "EDA_16939_Fase1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Node \- Estrutura de um nó da lista ligada de efeitos nefastos\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <matriz\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBlinha\fP"
.br
.ti -1c
.RI "int \fBcoluna\fP"
.br
.ti -1c
.RI "struct \fBNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Estrutura de um nó da lista ligada de efeitos nefastos\&. 
.PP
Definition at line \fB22\fP of file \fBmatriz\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Node::coluna"

.PP
Definition at line \fB23\fP of file \fBmatriz\&.h\fP\&.
.SS "int Node::linha"

.PP
Definition at line \fB23\fP of file \fBmatriz\&.h\fP\&.
.SS "struct \fBNode\fP* Node::next"

.PP
Definition at line \fB24\fP of file \fBmatriz\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EDA_16939_Fase1 from the source code\&.
