grafo.c
void inicializaGrafo(Grafo *g)
Inicializa o grafo (número de vértices) a 0.
g
int adicionaVertice(Grafo *g, int x, int y, char freq)
Adiciona uma nova antena (vértice) ao grafo.
g Apontador para o grafo x Coordenada x da antena y Coordenada y da antena freq Frequência de ressonância da antena ID atribuído ao novo vértice ou -1 se o grafo estiver cheio
Referenced by carregarMatrizParaGrafo.
void adicionaAresta(Grafo *g, int orig, int dest)
Adiciona uma aresta bidirecional entre dois vértices com a mesma frequência.
g Apontador para o grafo orig Vértice de origem dest Vértice de destino
Referenced by carregarMatrizParaGrafo.
void imprimeGrafo(Grafo *g)
Imprime todos os vértices do grafo e as suas ligações (arestas)
g Apontador
void dfs_visit(Grafo *g, int id, int *visitado)
Função auxiliar recursiva para DFS. Visita os vértices ligados ao atual.
g Apontador id Vértice atual visitado Array de vértices já visitados
References dfs_visit.
Referenced by dfs, dfs_visit.
void dfs(Grafo *g, int start_id)
Inicia a procura em profundidade (DFS) a partir de uma antena.
g Apontador start_id Antena de partida
References dfs_visit.
void bfs(Grafo *g, int start_id)
Inicia a procura em largura (BFS) a partir de uma antena.
g Apontador start_id Antena de partida
void listarCaminhosAux(Grafo *g, int atual, int destino, int *visitado, int *path, int path_len)
Função recursiva auxiliar para listar todos os caminhos entre duas antenas.
g Apontador atual Vértice atual destino Vértice de destino visitado Array de vértices já visitados path Array com o caminho atual path_len Comprimento atual do caminho
References listarCaminhosAux.
Referenced by listarCaminhos, listarCaminhosAux.
void listarCaminhos(Grafo *g, int origem, int destino)
Lista todos os caminhos possíveis entre duas antenas com a mesma frequência.
g Apontador origem Antena de origem destino Antena de destino
References listarCaminhosAux.